Fix unicode encode error in TargetVal.__str__
When baking a polish book on staging, we encounter a
`UnicodeEncodeError`:

```
Traceback (most recent call last):
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/tasks.py", line 31, in __call__
    return super(PyramidAwareTask, self).__call__(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/db.py", line 74, in wrapped
    return func(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/subscribers.py", line 167, in baking_processor
    bake(binder, recipe_id, publisher, message, cursor=cursor)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/db.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/bake.py", line 73, in bake
    binder = collate_models(binder, ruleset=recipe, includes=includes)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxepub/collation.py", line 68, in collate
    easybake(ruleset, raw_html, collated_html)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxepub/collation.py", line 38, in easybake
    oven.bake(html)
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxeasybake/oven.py", line 345, in bake
    strval = u''.join([u'{}'.format(s) for s in value])
  File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxeasybake/oven.py", line 123, in __unicode__
    self.el_id))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0106' in position 0: ordinal not in range(128)
```

After some investigation, this error actually comes from `TargetVal.__str__`:

```
r = str(self.collator.lookup(self.vtype,
                             self.vname,
                             self.el_id))
```

`self.collator.lookup` returned `Ćwiczenie 1.58` (in unicode) causing python 2
to error (python 3 is fine though).

Change `TargetVal.__str__` to only do `str()` on values that are not unicode or
string.

Fix openstax/cnx#302